name: Find Number Test
on: [push]
jobs:
  find_number_test:
    name: Find Number Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Produce Test 1 Output
      run: python find_lowest_number.py test_data/test1_input.txt test_output1.txt
    - name: Test 1
      run: diff test_data/test1_expected.txt test_output1.txt
    - name: Produce Test 2 Output
      run: python find_lowest_number.py test_data/test2_input.txt test_output2.txt
    - name: Test 2
      run: diff test_data/test2_expected.txt test_output2.txt
    - name: Produce Test 3 Output
      run: python find_lowest_number.py test_data/test3_input.txt test_output3.txt
    - name: Test 3
      run: test_data/test3_expected.txt test_output3.txt
